// Builds a structured A4 PDF from the Markdown report (no external library).
// Glyph widths of Helvetica / Helvetica-Bold for WinAnsi codes 32..255 (per 1000 units).
const W = [[278,278,355,556,556,889,667,191,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,278,278,584,584,584,556,1015,667,667,722,722,667,611,778,722,278,500,667,556,833,722,778,667,778,722,667,611,722,667,944,667,667,611,278,278,278,469,556,333,556,556,500,556,556,278,556,556,222,222,500,222,833,556,556,556,556,333,500,278,556,500,722,500,500,500,334,260,334,584,0,556,0,222,556,333,1000,556,556,333,1000,667,333,1000,0,611,0,0,222,222,333,333,350,556,1000,333,1000,500,333,944,0,500,500,278,333,556,556,556,556,260,556,333,737,370,556,584,333,737,333,400,584,333,333,333,556,537,278,333,333,365,556,834,834,834,611,667,667,667,667,667,667,1000,722,667,667,667,667,278,278,278,278,722,722,778,778,778,778,778,584,778,722,722,722,722,667,667,611,556,556,556,556,556,556,889,500,556,556,556,556,278,278,278,278,556,556,556,556,556,556,556,584,611,556,556,556,556,500,556,500], [278,333,474,556,556,889,722,238,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,333,333,584,584,584,611,975,722,722,722,722,667,611,778,722,278,556,722,611,833,722,778,667,778,722,667,611,722,667,944,667,667,611,333,278,333,584,556,333,556,611,556,611,556,333,611,611,278,278,556,278,889,611,611,611,611,389,556,333,611,556,778,556,556,500,389,280,389,584,0,556,0,278,556,500,1000,556,556,333,1000,667,333,1000,0,611,0,0,278,278,500,500,350,556,1000,333,1000,556,333,944,0,500,556,278,333,556,556,556,556,280,556,333,737,370,556,584,333,737,333,400,584,333,333,333,611,556,278,333,333,365,556,834,834,834,611,722,722,722,722,722,722,1000,722,667,667,667,667,278,278,278,278,722,722,778,778,778,778,778,584,778,722,722,722,722,667,667,611,556,556,556,556,556,556,889,556,556,556,556,556,278,278,278,278,611,611,611,611,611,611,611,584,611,611,611,611,611,556,611,556]];

const j = $input.first().json;
const lang = j.lang === 'fr' ? 'fr' : 'en';
const T = lang === 'fr'
  ? { title: 'Compte rendu de réunion', meeting: 'Réunion', participants: 'Participants', started: 'Début', ended: 'Fin', duration: 'Durée', footer: 'Généré automatiquement par votre assistant de réunion', page: 'Page' }
  : { title: 'Meeting report', meeting: 'Meeting', participants: 'Participants', started: 'Started', ended: 'Ended', duration: 'Duration', footer: 'Automatically generated by your meeting assistant', page: 'Page' };

const PW = 595.28, PH = 841.89, M = 50, BOTTOM = 58, CW = PW - 2 * M;
const ACC = [0.10, 0.27, 0.47], ACC2 = [0.17, 0.55, 0.75], ACC_LIGHT = [0.78, 0.85, 0.92];
const BODY = [0.15, 0.15, 0.17], GRAY = [0.45, 0.47, 0.50], BOX = [0.94, 0.96, 0.985], WHITE = [1, 1, 1];

// ---- text encoding (Unicode -> WinAnsi) and measuring ----
const CP = { 8364: 128, 8218: 130, 402: 131, 8222: 132, 8230: 133, 8224: 134, 8225: 135, 710: 136, 8240: 137, 352: 138, 8249: 139, 338: 140, 381: 142, 8216: 145, 8217: 146, 8220: 147, 8221: 148, 8226: 149, 8211: 150, 8212: 151, 732: 152, 8482: 153, 353: 154, 8250: 155, 339: 156, 382: 158, 376: 159 };
const REPL = { ' ': ' ', ' ': ' ', ' ': ' ', ' ': ' ', ' ': ' ', ' ': ' ', '​': '', '→': '->', '←': '<-', '✓': '+', '✔': '+', '≈': '~', '≤': '<=', '≥': '>=' };
const toBytes = (s) => {
  const out = [];
  for (const ch of String(s)) {
    if (REPL[ch] !== undefined) { for (const r of REPL[ch]) out.push(r.charCodeAt(0)); continue; }
    let c = ch.codePointAt(0);
    if (c === 9 || c === 10 || c === 13) c = 32;
    if (c >= 32 && c <= 126) out.push(c);
    else if (c >= 161 && c <= 255) out.push(c);
    else if (CP[c]) out.push(CP[c]);
    else if (c > 0xffff || c < 32) continue;
    else out.push(63);
  }
  return out;
};
const widthOf = (s, bold, size) => toBytes(s).reduce((a, c) => a + W[bold ? 1 : 0][c - 32], 0) * size / 1000;

// ---- page model: drawing operations per page, cursor y measured from the top ----
const pages = [[]];
let pageIdx = 0;
let y = M;
let contentTop = M;
const cur = () => pages[pageIdx];
const py = (yy) => (PH - yy).toFixed(2);
const col = (c) => c.map((v) => v.toFixed(3)).join(' ');
const text = (x, yTop, s, { bold = false, size = 10.5, color = BODY } = {}) => {
  if (!s) return;
  cur().push(`BT /${bold ? 'F2' : 'F1'} ${size} Tf ${col(color)} rg ${x.toFixed(2)} ${py(yTop)} Td <${Buffer.from(toBytes(s)).toString('hex')}> Tj ET`);
};
const rect = (x, yTop, w, h, color) => cur().push(`${col(color)} rg ${x.toFixed(2)} ${(PH - yTop - h).toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`);
const hline = (x1, x2, yTop, color, wd = 0.6) => cur().push(`${col(color)} RG ${wd} w ${x1.toFixed(2)} ${py(yTop)} m ${x2.toFixed(2)} ${py(yTop)} l S`);
const ensure = (h) => {
  if (y + h > PH - BOTTOM) { pages.push([]); pageIdx = pages.length - 1; y = M; contentTop = M; }
};

// ---- inline Markdown -> styled words, wrapped to a width ----
const cleanMd = (t) => t.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/`([^`]*)`/g, '$1').replace(/<br\s*\/?>/gi, ' ').replace(/^>\s?/, '');
const toRuns = (t) => cleanMd(t).split('**').map((p, i) => ({
  text: p.replace(/\*([^*\n]+)\*/g, '$1').replace(/(^|\s)_([^_\n]+)_(?=\s|$|[.,;:!?])/g, '$1$2'),
  bold: i % 2 === 1,
})).filter((r) => r.text);

const wrap = (runs, maxW, size, forceBold = false) => {
  const lines = [];
  let line = [], x = 0;
  for (const r of runs) {
    for (const wd of r.text.split(/\s+/).filter(Boolean)) {
      const bold = r.bold || forceBold;
      const pieces = [];
      let rest = wd;
      while (widthOf(rest, bold, size) > maxW && rest.length > 1) {
        let n = rest.length;
        while (n > 1 && widthOf(rest.slice(0, n), bold, size) > maxW) n--;
        pieces.push(rest.slice(0, n));
        rest = rest.slice(n);
      }
      pieces.push(rest);
      pieces.forEach((piece, pi) => {
        if (pi > 0 && line.length) { lines.push(line); line = []; x = 0; }
        const ww = widthOf(piece, bold, size);
        const gap = line.length ? widthOf(' ', bold, size) : 0;
        if (line.length && x + gap + ww > maxW) { lines.push(line); line = []; x = 0; }
        const g = line.length ? widthOf(' ', bold, size) : 0;
        line.push({ w: piece, bold, x: x + g });
        x += g + ww;
      });
    }
  }
  if (line.length) lines.push(line);
  return lines;
};
const drawLines = (lines, x0, size, lead, color = BODY) => {
  for (const ln of lines) {
    ensure(lead);
    for (const w of ln) text(x0 + w.x, y + size, w.w, { bold: w.bold, size, color });
    y += lead;
  }
};

// ---- cover band + meeting information box ----
const fmt = (iso) => {
  const d = new Date(iso);
  if (isNaN(d)) return String(iso || '-');
  return new Intl.DateTimeFormat(lang === 'fr' ? 'fr-FR' : 'en-GB', { dateStyle: 'long', timeStyle: 'short', timeZone: 'UTC' }).format(d) + ' (UTC)';
};
const mins = Math.round((new Date(j.ended_at) - new Date(j.started_at)) / 60000);
const durTxt = isNaN(mins) || mins < 0 ? '-' : mins >= 60 ? `${Math.floor(mins / 60)} h ${String(mins % 60).padStart(2, '0')} min` : `${mins} min`;
const seen = new Set();
const people = (j.participants || []).filter((p) => {
  const k = String(p).trim().toLowerCase();
  if (!k || seen.has(k)) return false;
  seen.add(k);
  return true;
});

rect(0, 0, PW, 104, ACC);
rect(0, 104, PW, 4, ACC2);
text(M, 52, T.title, { bold: true, size: 24, color: WHITE });
text(M, 78, `${T.meeting} : ${j.meeting_id || '-'}`, { size: 11.5, color: [0.85, 0.91, 0.97] });

const rows = [
  [T.participants, people.join(', ') || '-'],
  [T.started, fmt(j.started_at)],
  [T.ended, fmt(j.ended_at)],
  [T.duration, durTxt],
];
const LABEL_W = 88, PAD = 12;
const rowLines = rows.map(([, v]) => wrap(toRuns(v), CW - 2 * PAD - LABEL_W, 10.5));
const boxH = rowLines.reduce((a, l) => a + l.length * 15 + 5, 0) + 2 * PAD - 5;
rect(M, 128, CW, boxH, BOX);
rect(M, 128, 3, boxH, ACC2);
y = 128 + PAD;
rows.forEach(([label], i) => {
  text(M + PAD + 3, y + 10.5, label, { bold: true, size: 10.5, color: ACC });
  rowLines[i].forEach((ln, k) => ln.forEach((w) => text(M + PAD + 3 + LABEL_W + w.x, y + 10.5 + k * 15, w.w, { bold: w.bold, size: 10.5 })));
  y += rowLines[i].length * 15 + 5;
});
y = 128 + boxH + 22;
contentTop = y;

// ---- report body (Markdown) ----
const heading = (level, raw) => {
  const t = cleanMd(raw).replace(/\*/g, '').replace(/#+\s*$/, '').trim();
  if (level <= 2) {
    ensure(75);
    if (y > contentTop) y += 12;
    text(M, y + 14, t, { bold: true, size: 14, color: ACC });
    y += 20;
    hline(M, PW - M, y, ACC_LIGHT, 1);
    y += 10;
  } else {
    ensure(50);
    y += 6;
    text(M, y + 11.5, t, { bold: true, size: 11.5, color: BODY });
    y += 19;
  }
};
const bullet = (spaces, txt, label) => {
  const level = spaces < 2 ? 0 : Math.min(1 + Math.floor((spaces - 2) / 4), 3);
  const x = M + 8 + level * 16;
  const tx = x + (label ? 16 : 11);
  const lines = wrap(toRuns(txt), PW - M - tx, 10.5);
  ensure(14.5);
  text(x, y + 10.5, label || (level === 0 ? '•' : '–'), { size: 10.5, bold: !!label, color: ACC });
  drawLines(lines, tx, 10.5, 14.5);
  y += 3;
};
const paragraph = (txt) => {
  drawLines(wrap(toRuns(txt), CW, 10.5), M, 10.5, 15);
  y += 5;
};

for (const raw of String(j.report || '').replace(/\r/g, '').split('\n')) {
  const line = raw.replace(/\s+$/, '');
  if (!line.trim()) continue;
  let m;
  if ((m = line.match(/^\s{0,3}(#{1,6})\s+(.*)$/))) heading(m[1].length, m[2]);
  else if (/^\s*([-*_])(?:\s*\1){2,}\s*$/.test(line)) { ensure(14); y += 5; hline(M, PW - M, y, ACC_LIGHT); y += 9; }
  else if ((m = line.match(/^(\s*)[-*•+]\s+(.*)$/))) bullet(m[1].length, m[2]);
  else if ((m = line.match(/^(\s*)(\d+)[.)]\s+(.*)$/))) bullet(m[1].length, m[3], `${m[2]}.`);
  else if (line.trim().startsWith('|')) {
    if (/^[\s|:\-]+$/.test(line)) continue;
    paragraph(line.split('|').map((c) => c.trim()).filter(Boolean).join('  |  '));
  } else paragraph(line.trim());
}

// ---- footer on every page ----
const n = pages.length;
for (let i = 0; i < n; i++) {
  pageIdx = i;
  hline(M, PW - M, PH - 40, ACC_LIGHT, 0.6);
  text(M, PH - 26, T.footer, { size: 8, color: GRAY });
  const label = `${T.page} ${i + 1} / ${n}`;
  text(PW - M - widthOf(label, false, 8), PH - 26, label, { size: 8, color: GRAY });
}

// ---- assemble the PDF file ----
const safeId = String(j.meeting_id || 'meeting').replace(/[^A-Za-z0-9_-]/g, '') || 'meeting';
const objs = {};
objs[1] = '<< /Type /Catalog /Pages 2 0 R >>';
objs[2] = `<< /Type /Pages /Kids [${pages.map((_, i) => `${6 + 2 * i} 0 R`).join(' ')}] /Count ${n} >>`;
objs[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
objs[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';
objs[5] = `<< /Title (${T.title.replace(/[^\x20-\x7e]/g, 'e')} - ${safeId}) /Producer (n8n meeting assistant) >>`;
pages.forEach((ops, i) => {
  const content = ops.join('\n');
  objs[6 + 2 * i] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PW.toFixed(2)} ${PH.toFixed(2)}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${7 + 2 * i} 0 R >>`;
  objs[7 + 2 * i] = `<< /Length ${content.length} >>\nstream\n${content}\nendstream`;
});
const total = 5 + 2 * n;
let out = Buffer.from('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n', 'latin1');
const offsets = [];
for (let k = 1; k <= total; k++) {
  offsets[k] = out.length;
  out = Buffer.concat([out, Buffer.from(`${k} 0 obj\n${objs[k]}\nendobj\n`, 'latin1')]);
}
const xrefPos = out.length;
let xref = `xref\n0 ${total + 1}\n0000000000 65535 f \n`;
for (let k = 1; k <= total; k++) xref += `${String(offsets[k]).padStart(10, '0')} 00000 n \n`;
xref += `trailer\n<< /Size ${total + 1} /Root 1 0 R /Info 5 0 R >>\nstartxref\n${xrefPos}\n%%EOF\n`;
out = Buffer.concat([out, Buffer.from(xref, 'latin1')]);

const fileName = `${lang === 'fr' ? 'rapport' : 'report'}-${safeId}.pdf`;
const binary = await this.helpers.prepareBinaryData(out, fileName, 'application/pdf');
return [{ json: j, binary: { report: binary } }];
